
#ifndef ENUMS_H
#define ENUMS_H

enum {

	FALSO,
	VERDADERO
};

enum {

	SIN_ESTADO,
	AMAZONAS,
	ANZOATEGUI,
	APURE,
	ARAGUA,
	BARINAS,
	BOLIVAR,
	CARABOBO,
	COJEDES,
	DELTA_AMACURO,
	DISTRITO_CAPITAL,
	FALCON,
	GUARICO,
	LARA,
	MERIDA,
	MIRANDA,
	MONAGAS,
	NUEVA_ESPARTA,
	PORTUGUESA,
	SUCRE,
	TACHIRA,
	TRUJILLO,
	VARGAS,
	YARACUY,
	ZULIA,
	TOTAL_ESTADOS
};

enum {

	COLUMN_SEGUIMIENTO_ID,
	COLUMN_SEGUIMIENTO_BUSQUEDA,
	COLUMN_SEGUIMIENTO_NOMBRE_PRODUCTO,
	COLUMN_SEGUIMIENTO_FABRICANTE,
	COLUMN_SEGUIMIENTO_CATEGORIA,
	COLUMN_SEGUIMIENTO_PRECIO,
	COLUMN_SEGUIMIENTO_UNIDAD,
	COLUMN_SEGUIMIENTO_CANTIDAD_REQUERIDA,
	COLUMN_SEGUIMIENTO_PRESENTACION,
	COLUMN_SEGUIMIENTO_ESTADO,
	COLUMN_SEGUIMIENTO_MUNICIPIO,
	NUM_SEGUIMIENTO_COLUMNS
};

enum {

	COLUMN_ENCONTRADOS_AUTO,
	COLUMN_ENCONTRADOS_IMAGEN_ARCHIVADO,
	COLUMN_ENCONTRADOS_NOMBRE_PRODUCTO,
	COLUMN_ENCONTRADOS_CATEGORIA,
	COLUMN_ENCONTRADOS_STOCK,
	COLUMN_ENCONTRADOS_PRECIO,
	COLUMN_ENCONTRADOS_ESTADO,
	COLUMN_ENCONTRADOS_MUNICIPIO,
	COLUMN_ENCONTRADOS_DIRECCION,
	COLUMN_ENCONTRADOS_TELEFONO_EMPRESA,
	COLUMN_ENCONTRADOS_NOMBRE_EMPRESA,
	COLUMN_ENCONTRADOS_REPUTACION,
	NUM_ENCONTRADOS_COLUMNS
};

enum {

	COLUMN_MIS_PRODUCTOS_ID,
	COLUMN_MIS_PRODUCTOS_NOMBRE_PRODUCTO,
	COLUMN_MIS_PRODUCTOS_FABRICANTE,
	COLUMN_MIS_PRODUCTOS_CATEGORIA,
	COLUMN_MIS_PRODUCTOS_STOCK,
	COLUMN_MIS_PRODUCTOS_PRECIO,
	COLUMN_MIS_PRODUCTOS_UNIDAD,
	COLUMN_MIS_PRODUCTOS_PRESENTACION,
	COLUMN_MIS_PRODUCTOS_VISITAS,
	NUM_MIS_PRODUCTOS_COLUMNS
};

enum {

	COLUMN_PROVEEDORES_ID,
	COLUMN_PROVEEDORES_NOMBRE_PRODUCTO,
	COLUMN_PROVEEDORES_REPUTACION_GENERAL,
	COLUMN_PROVEEDORES_REPUTACION_LOCAL,
	COLUMN_PROVEEDORES_NOMBRE_EMPRESA,
	COLUMN_PROVEEDORES_CATEGORIA,
	COLUMN_PROVEEDORES_STOCK,
	COLUMN_PROVEEDORES_PRECIO,
	COLUMN_PROVEEDORES_ESTADO,
	COLUMN_PROVEEDORES_MUNICIPIO,
	COLUMN_PROVEEDORES_DIRECCION,
	NUM_PROVEEDORES_COLUMNS
};


#endif
